routes/admin.php
<?php

use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\MerchantController;
use App\Http\Controllers\Admin\MemberController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\MenuController;
use App\Http\Controllers\Admin\LevelController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\MemberAddressController;
use App\Http\Controllers\Admin\GalleryController;
use App\Http\Controllers\Admin\TrackingOrderController;
use App\Http\Controllers\Admin\ContactUsController;
use App\Http\Controllers\Admin\PaymentController;
use App\Http\Controllers\Admin\UnitController;
use App\Http\Controllers\Admin\ShippingVendorController;
use App\Http\Controllers\Admin\PackageController;
use App\Http\Controllers\Admin\CustomerController;
use App\Http\Controllers\Admin\CompanyController;
use App\Http\Controllers\Admin\CompanyPackageController;
use App\Http\Controllers\Admin\ForgotPasswordController;
use App\Http\Controllers\Admin\InvoiceController;
use App\Http\Controllers\Admin\StockLogController;
use App\Http\Controllers\Admin\RefundController;
use App\Http\Controllers\Admin\OutletController;
use App\Http\Controllers\Admin\WarehouseController;
use App\Http\Controllers\Admin\QuotationController;
use App\Http\Controllers\Admin\ReportOrderController;
use App\Http\Controllers\Admin\ReportProductController;
use App\Http\Controllers\Admin\ProcurementController;
use App\Http\Controllers\Admin\ReportController;
use App\Http\Controllers\Admin\BankController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('admin')->name('admin.')->group(function () {
    Route::get('/login', [AuthController::class, 'index'])->name('login');
    Route::post('/login', [AuthController::class, 'login'])->name('login.submit');

    Route::get('forget-password', [ForgotPasswordController::class, 'showForgetPasswordForm'])->name('forget.password.get');
    Route::post('forget-password', [ForgotPasswordController::class, 'submitForgetPasswordForm'])->name('forget.password.post');
    Route::get('reset-password/{token}', [ForgotPasswordController::class, 'showResetPasswordForm'])->name('reset.password.get');
    Route::post('reset-password', [ForgotPasswordController::class, 'submitResetPasswordForm'])->name('reset.password.post');

    Route::middleware(['auth', 'check.expired'])->group(function () {
        Route::get('/logout', [AuthController::class, 'logout'])->name('logout');
        Route::get('/', [HomeController::class, 'index'])->name('dashboard');
        //timpa route update karena upload image formdata harus pake post biar inputannya masuk ke controller
        Route::post('roles/{role}', [RoleController::class, 'update'])->name('admin.roles.update');
        Route::resource('roles', RoleController::class);

        Route::post('permissions/{permission}', [PermissionController::class, 'update'])->name('admin.permissions.update');
        Route::resource('permissions', PermissionController::class);

        // Route::get('member/diagram/{member_id}', [MemberController::class, 'diagram'])->name('member.diagram');
        // Route::get('member/level/{member_id}', [MemberController::class, 'level'])->name('member.level');
        // Route::resource('member', MemberController::class);

        // Route::get('member/member-address/{member_id}', [MemberAddressController::class, 'index'])->name('member.member-address');
        // Route::get('member/member-address/show/{id}', [MemberAddressController::class, 'show'])->name('member.member-address.show');
        // Route::post('member/member-address/{member_id}/store', [MemberAddressController::class, 'store'])->name('member.member-address.store');
        // Route::put('member/member-address/update/{id}', [MemberAddressController::class, 'update'])->name('member.member-address.update');
        // Route::delete('member/member-address/destroy/{id}', [MemberAddressController::class, 'destroy'])->name('member.member-address.destroy');
        // Route::post('banks/{bank}', [BankController::class, 'update'])->name('banks.update');
        Route::resource('banks', BankController::class);
        Route::get('banks/detail/{id}', [BankController::class, 'detail'])->name('banks.detail');
        


        Route::post('menus/{menu}', [MenuController::class, 'update'])->name('admin.menus.update');
        Route::resource('menus', MenuController::class);

        Route::post('users/{user}', [UserController::class, 'update'])->name('admin.users.update');
        Route::get('users/detail/{id}', [UserController::class, 'userDetail'])->name('users.detail');
        Route::resource('users', UserController::class);

        // Route::post('levels/{level}', [LevelController::class, 'update'])->name('admin.levels.update');
        // Route::resource('levels', LevelController::class);

        // Route::resource('merchants', MerchantController::class);
        // Route::get('products/{id}', [ProductController::class, 'show'])->name('admin.products.show');
        // Route::post('products/{id}', [ProductController::class, 'update'])->name('admin.products.update');
        Route::get('products/product-images/{id}', [ProductController::class, 'productImages'])->name('admin.products.product-images');
        Route::get('product/get-list', [ProductController::class, 'getList'])->name('products.get-list');
        Route::post('products', [ProductController::class, 'update'])->name('products.update');
        Route::resource('products', ProductController::class);
        Route::get('products/show/{id}', [ProductController::class, 'detail'])->name('products.detail');
        Route::get('product/report', [ReportProductController::class, 'index'])->name('product.report');
        Route::get('product/report/records', [ReportProductController::class, 'records'])->name('product.report.records');

        Route::resource('categories', CategoryController::class);
        Route::get('category/detail/{id}', [CategoryController::class, 'detailCategory'])->name('category.show');

        // Route::resource('orders', OrderController::class);

        Route::prefix('orders')->name('orders.')->group(function () {
            Route::get('', [OrderController::class, 'index'])->name('index');
            Route::get('/create', [OrderController::class, 'create'])->name('create');
            Route::post('/store', [OrderController::class, 'store'])->name('store');
            Route::post('/update/{id}', [OrderController::class, 'update'])->name('update');
            Route::delete('/destroy/{id}', [OrderController::class, 'destroy'])->name('destroy');
            Route::get('/get-address', [OrderController::class, 'getAddress'])->name('get-address');
            Route::get('/show/{order_id}', [OrderController::class, 'show'])->name('show');
            Route::get('/edit/{order_id}', [OrderController::class, 'edit'])->name('edit');
            Route::get('/update-status/{order_id}', [OrderController::class, 'updateStatus'])->name('update-status');
            Route::get('/edit-resi/{order_id}', [OrderController::class, 'showResi'])->name('show-resi');
            Route::put('/edit-resi/{order_id}', [OrderController::class, 'addResi'])->name('edit-resi');
            Route::resource('{orderId}/refunds', RefundController::class);
            Route::get('refunds/{refund_id}/details', [RefundController::class, 'getDetails'])->name('refunds.get-details');
            Route::get('refunds/{refund_id}/print', [RefundController::class, 'print'])->name('refunds.print');
            Route::get('/print/{id}', [OrderController::class, 'printOrder'])->name('print');
            Route::get('/print-preview/{id}', [OrderController::class, 'generatePrintOrder'])->name('print-preview');
            Route::get('/print-struk/{id}', [OrderController::class, 'PrintStruck'])->name('print-struk');
        });

        Route::get('quotation', [QuotationController::class, 'index'])->name('quotation.index');
        Route::get('quotation/create', [QuotationController::class, 'create'])->name('quotation.create');
        Route::post('quotation/store', [QuotationController::class, 'store'])->name('quotation.store');
        Route::post('quotation/update/{id}', [QuotationController::class, 'update'])->name('quotation.update');
        Route::delete('quotation/destroy/{id}', [QuotationController::class, 'destroy'])->name('quotation.destroy');
        Route::get('quotation/show/{id}', [QuotationController::class, 'show'])->name('quotation.show');
        Route::get('quotation/edit/{id}', [QuotationController::class, 'edit'])->name('quotation.edit');
        Route::get('quotation/convert-order/{id}', [QuotationController::class, 'convertOrder'])->name('quotation.convert-order');
        Route::get('quotation/print-pdf/{id}', [QuotationController::class, 'printQuotation'])->name('quotation.print');
        Route::get('quotation/print-invoice/{id}', [QuotationController::class, 'generatePrintInvoice'])->name('quotation.print-invoice');

        // Route::get('quotation/print/{id}', [QuotationController::class, 'printget'])->name('quotation.printget');

        Route::get('profile', [ProfileController::class, 'index'])->name('profile');
        Route::post('profile', [ProfileController::class, 'update'])->name('profile.update');

routes/web.php
<?php
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\ShopController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\Member\AuthController;
use App\Http\Controllers\ChangePasswordController;
use App\Http\Controllers\Member\ProfileController;
use App\Http\Controllers\Member\WishlistController;
use App\Http\Controllers\Member\HistoryOrderController;
use App\Http\Controllers\ContactUsController;
use App\Http\Controllers\MerchantController;
use App\Http\Controllers\Member\MemberAddressController;
use App\Http\Controllers\Member\PaymentController;
use App\Http\Controllers\Member\RatingController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/store/{name}', [ProductController::class, 'index'])->name('store.index');
// Route::get('/product/show/{name}', [ProductController::class, 'show'])->name('products.show');


//ordergit 
Route::get('/order/cart', [OrderController::class, 'cart'])->name('order.cart');
Route::get('/order/checkout', [OrderController::class, 'checkout'])->name('order.checkout');
Route::get('/add-to-cart/{id}', [OrderController::class, 'addToCart'])->name('product.addToCart');
Route::get('/cart-remove/{id}', [OrderController::class, 'deleteCart'])->name('order.cart.delete');
Route::get('/invoice/{id}', [OrderController::class, 'invoice'])->name('order.invoice');
Route::post('/checkout', [OrderController::class, 'checkoutStore'])->name('order.checkout.submit');

app/Http/Controllers/API/ProductController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Product;
use App\Models\StockLog;
// use App\Models\ProductImage;
use App\Helpers\FileHelper;
use Illuminate\Support\Facades\Auth;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        try {
            $payload = $request->all();

            if (Auth::user()->hasRole('superadmin')) {
                $data = Product::orderBy('created_at', 'desc')->orderBy('name', 'ASC');
            } else {
                $data = Product::where('company_id', Auth::user()->company_id)->orderBy('created_at', 'desc')->orderBy('name', 'ASC');
            }
            
            if ( isset($payload['sku_code'])) {
                $data = $data->where('sku_code', $payload['sku_code']);
            }elseif ( isset($payload['search'])){
                $data = $data->where('name', 'like', '%'.$payload['search'].'%');
            }
            
            $data = $data->paginate(10);

            $response["code"] = 200;
        } catch (\Exception $ex) {
            $response = [
                'code' => 500,
                'message' => $ex->getMessage(),
                'data' => null
            ];
        }

        return response()->json($data, $response['code']);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $this->validate($request, [
                'name'          => ['required'],
                'price'         => ['required'],
                // 'stock'         => ['required'],
                // 'company_id'    => ['required'],
                'category_id'   => ['required'],
            ]);
            $input = $request->all();
            // dd($input);

            $input['company_id'] = Auth::user()->hasRole('superadmin') ? $request['company_id'] : $request['company_id'] = Auth::user()->company_id;

            isset($input['is_service']) && $input['is_service'] == 1 ? $input['stock'] = NULL : '' ;

            $product = Product::create($input);

            $response = [
                'code' => 200,
                'message' => 'successfully',
                'data' => $product
            ];
        } catch (\Exception $ex) {
            $response = [
                'code' => 500,
                'message' => $ex->getMessage(),
                'data' => null
            ];
        }

        return response()->json($response, $response['code']);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        try {
            $data = Product::find($id);

            $response = [
                'code' => 200,
                'message' => 'successfully',
                'data' => $data
            ];
        } catch (\Exception $ex) {
            $response = [
                'code' => 500,
                'message' => $ex->getMessage(),
                'data' => null
            ];
        }

        return response()->json($response, $response['code']);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $input = $request->all();
            $product = Product::find($id);
            
            isset($input['is_service']) && $input['is_service'] == 1 ? $input['stock'] = NULL : '' ;

            $input['company_id'] = Auth::user()->hasRole('superadmin') ? $request['company_id'] : $request['company_id'] = Auth::user()->company_id;

            $data = $product->update($input);

            $response = [
                'code' => 200,
                'message' => 'successfully update product ' .$product->name,
                'data' => $product
            ];
        } catch (\Exception $ex) {
            $response = [
                'code' => 500,
                'message' => $ex->getMessage(),
                'data' => null
            ];
        }

        return response()->json($response, $response['code']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            // ProductImage::whereProductId($id)->delete();
            $product = Product::find($id);
            $product->delete();

            $response = [
                'code' => 200,
                'message' => 'successfully deleted',
                'data' => $product
            ];
        } catch (\Exception $ex) {
            $response = [
                'code' => 500,
                'message' => $ex->getMessage(),
                'data' => null
            ];
        }

        return response()->json($response, $response['code']);
    }

    public function stockLog($product)
    {
        try {
            $data = StockLog::whereProductId($product)->get();

            $response = [
                'code' => 200,
                'message' => 'successfully',
                'data' => $data
            ];
        } catch (\Exception $ex) {
            $response = [
                'code' => 500,
                'message' => $ex->getMessage(),
                'data' => null
            ];
        }

        return response()->json($response, $response['code']);
    }
}

resources/views/pages/admin/products/action.blade.php
<div class="dropdown">
    <button class="btn btn-sm btn-primary dropdown-toggle" type="button" id="dropdownMenuAction" data-bs-toggle="dropdown"
        aria-expanded="false">
        Action
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuAction">
        <li><a class="dropdown-item" href="{{ route('admin.products.detail', $product->id) }}">Show</a></li>
        <li><a class="dropdown-item edit-btn" href="#" data-id="{{ $product->id }}">Edit</a></li>
        <li>
            <hr class="dropdown-divider">
        </li>
        <li><a class="dropdown-item delete-btn" data-id="{{ $product->id }}" href="#">Delete</a></li>
    </ul>
</div>

resources/views/pages/admin/products/detail.blade.php
@extends('layouts.admin.app')
@section('content')
    <!--begin::Container-->
    <div id="kt_content_container" class="d-flex flex-column-fluid align-items-start container-xxl">
        <!--begin::Post-->
        <div class="content flex-row-fluid" id="kt_content">
            <!--begin::Order details page-->
            <div class="d-flex flex-column gap-7 gap-lg-10">
                <!--begin::Order summary-->
                <div class="d-flex flex-column flex-xl-row gap-7 gap-lg-10">
                    <!--begin::Order details-->
                    <div class="card card-flush py-4 flex-row-fluid">

                        <div class="card-body pt-0">
                            <div class="card-title">
                                <div class="row">
                                    <div class="col-md-6">
                                        <h3 class="mt-2">Product Detail</h3>
                                    </div>

                                    <div class="col-md-6">
                                        <div class="d-flex justify-content-end">
                                            <!-- <button class="btn btn-md-primary" onclick="history.back()">Back</button> -->
                                            <!-- <a href="#"  class="btn btn-white">White</a> -->
                                            <a href="#" onclick="history.back()" class="btn btn-primary">Back</a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <table class="table align-middle table-row-bordered mb-0 fs-6 gy-5 min-w-300px">
                                <!--begin::Table body-->
                                <tbody class="fw-semibold text-gray-600">
                                    <!--begin::Customer name-->
                                    <tr>
                                        <td class="text-muted">
                                            <div class="d-flex align-items-center"> Name
                                            </div>
                                            <pre>
                                            </pre>
                                            <!--begin::Name-->
                                            <a href="#" class="text-gray-600 text-hover-primary">{{ $data->name }}</a>
                                            <!--end::Name-->
                                        </td>
                                        <td class="fw-bold text-end">
                                            <div class="d-flex align-items-center justify-content-end">
                                            </div>
                                        </td>
                                    </tr>


                                </tbody>
                                <!--end::Table body-->
                            </table>
                        </div>
                        <!--end::Card body-->
                    </div>
                    <!--end::Order details-->
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/admin/products/form.blade.php
<!--begin::Modal-->
<div class="modal fade" tabindex="-1" id="product-modal" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-scrollable">
        <form method="post" action="" class="form needs-validation" id="product-form" enctype="multipart/form-data" autocomplete="off" novalidate>
            @csrf
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Form Produk</h5>

                    <!--begin::Close-->
                    <div class="btn btn-icon btn-sm btn-active-light-primary ms-2" data-bs-dismiss="modal" aria-label="Close">
                        <span class="svg-icon svg-icon-2x"></span>
                    </div>
                    <!--end::Close-->
                </div>

                <div class="modal-body">

                    <div class="mb-10 fv-row">
                        <label for="name" class="required form-label"> Name</label>
                        <input type="text" class="form-control form-control-solid" name="name" placeholder="Name" required />
                    </div>

                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
                    <button class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </form>
    </div>
</div>
<!--end::Modal-->

resources/views/pages/admin/products/index.blade.php
@extends('layouts.admin.app')
@section('content')
    <!--begin::Container-->
    <div id="container" class="d-flex flex-column-fluid align-items-start container-xxl">
        <!--begin::Post-->
        {{-- {{dd($categories)}} --}}
        <div class="content flex-row-fluid">
            <!--begin::Card-->
            <div class="card">
                <div class="card-header border-0 pt-6 d-flex justify-content-end">
                    <button type="button" class="btn btn-primary btn btn-primary btn-hover-scale" data-bs-toggle="modal"
                        data-bs-target="#product-modal">
                        <i class="la la-plus"></i> Create
                    </button>
                </div>
                <!--begin::Card body-->
                <div class="card-body py-4">
                    <!--begin::Table-->
                    <div class="table-responsive">
                        {{ $dataTable->table() }}
                    </div>
                    <!--end::Table-->
                </div>
                <!--end::Card body-->
            </div>
            <!--end::Card-->
        </div>
        <!--end::Post-->
    </div>
    <!--end::Container-->
    <div class="row">
        <div class="col-md-12">

        </div>
    </div>
    <a href=""></a>

    @include('pages.' . $path . '.' . $view . '.form')
@endsection

@push('scripts')
    {{ $dataTable->scripts() }}
    <script>
        $(document).ready(function() {
            let method = 'POST'
            //STORE
            $('#product-form').submit(function(e) {
                e.preventDefault()
                const payload = new FormData(this)
                const url = $(this).attr('action')
                const validator = document.getElementById('product-form').checkValidity()

                if (method != 'POST')
                    payload.append('_method', 'PUT');

                if (validator) {
                    $.ajax({
                            url: url,
                            headers: {
                                'X-CSRF-TOKEN': '{{ csrf_token() }}'
                            },
                            method: method,
                            method: 'POST',
                            data: payload,
                            async: false,
                            cache: false,
                            contentType: false,
                            enctype: 'multipart/form-data',
                            processData: false,
                        })
                        .done(response => {
                            if (response.success) {
                                Swal.fire({
                                    icon: 'success',
                                    title: 'Success',
                                    text: response.message
                                })

                                $('.dataTable').DataTable().ajax.reload()
                                $('#product-modal').modal('hide')
                            }
                        })
                        .fail(response => {
                            Swal.fire({
                                icon: 'error',
                                title: 'Error',
                                text: response.responseJSON.message
                            })
                        })
                }

            })

            //DELETE
            $(document).on('click', '.delete-btn', function() {
                Swal.fire({
                    title: 'Are you sure',
                    icon: 'info',
                    showDenyButton: true,
                    confirmButtonText: 'Yes',
                    denyButtonText: `No`,
                }).then((result) => {
                    /* Read more about isConfirmed, isDenied below */
                    if (result.isConfirmed) {
                        const url = '{{ url('admin/products') }}/' + $(this).data('id')
                        $.ajax({
                            url: url,
                            method: 'DELETE',
                            headers: {
                                'X-CSRF-TOKEN': '{{ csrf_token() }}'
                            }
                        }).done(response => {
                            console.log(response)
                            Swal.fire({
                                icon: 'success',
                                title: 'Success',
                                message: response.message
                            })
                            $('.dataTable').DataTable().ajax.reload()
                        })
                    }
                })
            })

            //EDIT
            $(document).on('click', '.edit-btn', function() {
                const url = '{{ url('admin/products') }}/' + $(this).data('id')
                $('#product-form').attr('action', url)
                method = 'PUT'

                let data = {}
                $.get(url).done(response => {
                    if (response.success) data = response.data
                    setForm(data)
                    $('#product-modal').modal('show')
                })
            })

            function setForm(data) {
                $('input[name=name]').val(data.name)
            }

            $('.modal').on('hidden.bs.modal', function(event) {
                $('#product-form').attr('action', '{{ route('admin.products.store') }}')
                method = 'POST'
            })

        })
    </script>
@endpush