routes/admin.php
<?php

use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\MerchantController;
use App\Http\Controllers\Admin\MemberController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\MenuController;
use App\Http\Controllers\Admin\LevelController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\MemberAddressController;
use App\Http\Controllers\Admin\GalleryController;
use App\Http\Controllers\Admin\TrackingOrderController;
use App\Http\Controllers\Admin\ContactUsController;
use App\Http\Controllers\Admin\PaymentController;
use App\Http\Controllers\Admin\UnitController;
use App\Http\Controllers\Admin\ShippingVendorController;
use App\Http\Controllers\Admin\PackageController;
use App\Http\Controllers\Admin\CustomerController;
use App\Http\Controllers\Admin\CompanyController;
use App\Http\Controllers\Admin\CompanyPackageController;
use App\Http\Controllers\Admin\ForgotPasswordController;
use App\Http\Controllers\Admin\InvoiceController;
use App\Http\Controllers\Admin\StockLogController;
use App\Http\Controllers\Admin\RefundController;
use App\Http\Controllers\Admin\OutletController;
use App\Http\Controllers\Admin\WarehouseController;
use App\Http\Controllers\Admin\QuotationController;
use App\Http\Controllers\Admin\ReportOrderController;
use App\Http\Controllers\Admin\ReportProductController;
use App\Http\Controllers\Admin\ProcurementController;
use App\Http\Controllers\Admin\ReportController;
use App\Http\Controllers\Admin\BankController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('admin')->name('admin.')->group(function () {
    Route::get('/login', [AuthController::class, 'index'])->name('login');
    Route::post('/login', [AuthController::class, 'login'])->name('login.submit');

    Route::get('forget-password', [ForgotPasswordController::class, 'showForgetPasswordForm'])->name('forget.password.get');
    Route::post('forget-password', [ForgotPasswordController::class, 'submitForgetPasswordForm'])->name('forget.password.post');
    Route::get('reset-password/{token}', [ForgotPasswordController::class, 'showResetPasswordForm'])->name('reset.password.get');
    Route::post('reset-password', [ForgotPasswordController::class, 'submitResetPasswordForm'])->name('reset.password.post');

    Route::middleware(['auth', 'check.expired'])->group(function () {
        Route::get('/logout', [AuthController::class, 'logout'])->name('logout');
        Route::get('/', [HomeController::class, 'index'])->name('dashboard');
        //timpa route update karena upload image formdata harus pake post biar inputannya masuk ke controller
        Route::post('roles/{role}', [RoleController::class, 'update'])->name('admin.roles.update');
        Route::resource('roles', RoleController::class);

        Route::post('permissions/{permission}', [PermissionController::class, 'update'])->name('admin.permissions.update');
        Route::resource('permissions', PermissionController::class);

        // Route::get('member/diagram/{member_id}', [MemberController::class, 'diagram'])->name('member.diagram');
        // Route::get('member/level/{member_id}', [MemberController::class, 'level'])->name('member.level');
        // Route::resource('member', MemberController::class);

        // Route::get('member/member-address/{member_id}', [MemberAddressController::class, 'index'])->name('member.member-address');
        // Route::get('member/member-address/show/{id}', [MemberAddressController::class, 'show'])->name('member.member-address.show');
        // Route::post('member/member-address/{member_id}/store', [MemberAddressController::class, 'store'])->name('member.member-address.store');
        // Route::put('member/member-address/update/{id}', [MemberAddressController::class, 'update'])->name('member.member-address.update');
        // Route::delete('member/member-address/destroy/{id}', [MemberAddressController::class, 'destroy'])->name('member.member-address.destroy');
        // Route::post('banks/{bank}', [BankController::class, 'update'])->name('banks.update');
        Route::resource('banks', BankController::class);
        Route::get('banks/detail/{id}', [BankController::class, 'detail'])->name('banks.detail');
        


        Route::post('menus/{menu}', [MenuController::class, 'update'])->name('admin.menus.update');
        Route::resource('menus', MenuController::class);

        Route::post('users/{user}', [UserController::class, 'update'])->name('admin.users.update');
        Route::get('users/detail/{id}', [UserController::class, 'userDetail'])->name('users.detail');
        Route::resource('users', UserController::class);

        // Route::post('levels/{level}', [LevelController::class, 'update'])->name('admin.levels.update');
        // Route::resource('levels', LevelController::class);

        // Route::resource('merchants', MerchantController::class);
        // Route::get('products/{id}', [ProductController::class, 'show'])->name('admin.products.show');
        // Route::post('products/{id}', [ProductController::class, 'update'])->name('admin.products.update');
        Route::get('products/product-images/{id}', [ProductController::class, 'productImages'])->name('admin.products.product-images');
        Route::get('product/get-list', [ProductController::class, 'getList'])->name('products.get-list');
        Route::post('products', [ProductController::class, 'update'])->name('products.update');
        Route::resource('products', ProductController::class);
        Route::get('products/show/{id}', [ProductController::class, 'detail'])->name('products.detail');
        Route::get('product/report', [ReportProductController::class, 'index'])->name('product.report');
        Route::get('product/report/records', [ReportProductController::class, 'records'])->name('product.report.records');

        Route::resource('categories', CategoryController::class);
        Route::get('category/detail/{id}', [CategoryController::class, 'detailCategory'])->name('category.show');

        // Route::resource('orders', OrderController::class);

        Route::prefix('orders')->name('orders.')->group(function () {
            Route::get('', [OrderController::class, 'index'])->name('index');
            Route::get('/create', [OrderController::class, 'create'])->name('create');
            Route::post('/store', [OrderController::class, 'store'])->name('store');
            Route::post('/update/{id}', [OrderController::class, 'update'])->name('update');
            Route::delete('/destroy/{id}', [OrderController::class, 'destroy'])->name('destroy');
            Route::get('/get-address', [OrderController::class, 'getAddress'])->name('get-address');
            Route::get('/show/{order_id}', [OrderController::class, 'show'])->name('show');
            Route::get('/edit/{order_id}', [OrderController::class, 'edit'])->name('edit');
            Route::get('/update-status/{order_id}', [OrderController::class, 'updateStatus'])->name('update-status');
            Route::get('/edit-resi/{order_id}', [OrderController::class, 'showResi'])->name('show-resi');
            Route::put('/edit-resi/{order_id}', [OrderController::class, 'addResi'])->name('edit-resi');
            Route::resource('{orderId}/refunds', RefundController::class);
            Route::get('refunds/{refund_id}/details', [RefundController::class, 'getDetails'])->name('refunds.get-details');
            Route::get('refunds/{refund_id}/print', [RefundController::class, 'print'])->name('refunds.print');
            Route::get('/print/{id}', [OrderController::class, 'printOrder'])->name('print');
            Route::get('/print-preview/{id}', [OrderController::class, 'generatePrintOrder'])->name('print-preview');
            Route::get('/print-struk/{id}', [OrderController::class, 'PrintStruck'])->name('print-struk');
        });

        Route::get('quotation', [QuotationController::class, 'index'])->name('quotation.index');
        Route::get('quotation/create', [QuotationController::class, 'create'])->name('quotation.create');
        Route::post('quotation/store', [QuotationController::class, 'store'])->name('quotation.store');
        Route::post('quotation/update/{id}', [QuotationController::class, 'update'])->name('quotation.update');
        Route::delete('quotation/destroy/{id}', [QuotationController::class, 'destroy'])->name('quotation.destroy');
        Route::get('quotation/show/{id}', [QuotationController::class, 'show'])->name('quotation.show');
        Route::get('quotation/edit/{id}', [QuotationController::class, 'edit'])->name('quotation.edit');
        Route::get('quotation/convert-order/{id}', [QuotationController::class, 'convertOrder'])->name('quotation.convert-order');
        Route::get('quotation/print-pdf/{id}', [QuotationController::class, 'printQuotation'])->name('quotation.print');
        Route::get('quotation/print-invoice/{id}', [QuotationController::class, 'generatePrintInvoice'])->name('quotation.print-invoice');

        // Route::get('quotation/print/{id}', [QuotationController::class, 'printget'])->name('quotation.printget');

        Route::get('profile', [ProfileController::class, 'index'])->name('profile');
        Route::post('profile', [ProfileController::class, 'update'])->name('profile.update');

routes/web.php
<?php
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\ShopController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\Member\AuthController;
use App\Http\Controllers\ChangePasswordController;
use App\Http\Controllers\Member\ProfileController;
use App\Http\Controllers\Member\WishlistController;
use App\Http\Controllers\Member\HistoryOrderController;
use App\Http\Controllers\ContactUsController;
use App\Http\Controllers\MerchantController;
use App\Http\Controllers\Member\MemberAddressController;
use App\Http\Controllers\Member\PaymentController;
use App\Http\Controllers\Member\RatingController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/store/{name}', [ProductController::class, 'index'])->name('store.index');
// Route::get('/product/show/{name}', [ProductController::class, 'show'])->name('products.show');


//ordergit 
Route::get('/order/cart', [OrderController::class, 'cart'])->name('order.cart');
Route::get('/order/checkout', [OrderController::class, 'checkout'])->name('order.checkout');
Route::get('/add-to-cart/{id}', [OrderController::class, 'addToCart'])->name('product.addToCart');
Route::get('/cart-remove/{id}', [OrderController::class, 'deleteCart'])->name('order.cart.delete');
Route::get('/invoice/{id}', [OrderController::class, 'invoice'])->name('order.invoice');
Route::post('/checkout', [OrderController::class, 'checkoutStore'])->name('order.checkout.submit');

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Category;
use App\Models\Member;
use Illuminate\Support\Facades\Session;

use View;
use RealRashid\SweetAlert\Facades\Alert;
use Illuminate\Support\Facades\Auth;
use App\Helpers\FileHelper;


use App\Models\Product;
use App\Models\MemberAddress;
use App\Models\Quotation;
use App\Models\Outlet;
use App\Models\User;
use App\Models\Company;
use App\Models\QuotationDetail;

use App\Http\Requests\CheckoutRequest;

class OrderController extends Controller
{
    protected $categories;

    public function __construct()
    {
        $this->view     = "front-end.order.";
        $this->categories = Category::all();

    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function cart()
    {
        return view('pages.' . $this->view . 'cart');
    }

    public function checkout()
    {
        $company    = Company::first();
        $outlets    = Outlet::get();
        $cashiers   = User::whereType('cashier')->get();
        return view('pages.'. $this->view.'checkout', compact('company', 'outlets', 'cashiers'));
    }

    public function addToCart(Request $request, $id)
    {
        $product = Product::find($id);
        $cart = session()->get('cart');
        // dd($cart);

        $cart[$id] = [
            'product_id'        => $product->id,
            "company_id "       => $product->company_id,
            "category_id"       => $product->category_id,
            "name"              => $product->name,
            "description"       => $product->description,
            "price"             => $product->price,
            "stock"             => $product->stock,
            "total"             => $product->price,
            "qty"               => 1,
        ];

        session(['cart' => $cart]);
        $this->cartTotalOrder();

        Alert::success('Berhasil', 'Barang berhasil ditambahkan ke keranjang');
        return redirect()->route('order.cart');
    }

    public function cartTotalOrder(){

        $carts = session('cart');
        if (!$carts) {
            return true;
        } else {
            $qty    = 0;
            $total  = 0;
            foreach($carts as $key=>$data){
                $qty += $data['qty'];
                $total += $data['total'];
            }

            session(['cart_total' => $qty]);
            session(['cart_grand_total' => $total]);
        }

        return true;
    }

    public function deleteCart($id) {
        if ($id == 'all') {
            session()->forget('cart');
        } else {
            $cart = session('cart');
            unset($cart[$id]);

            session(['cart' => $cart]);
        }

        $this->cartTotalOrder();

        return redirect()->route('order.cart');
    }

    public function checkoutStore(Request $request)
    {
        try {
            $carts = session('cart');
            $company = Company::first();

            $input = $request->all();

            $quotation_data = [
                'name_buyer'        => $input['name_buyer'],
                'no_rek_buyer'      => $input['no_rek_buyer'],
                'quotation_code'    => quotation_code(),
                'date'              => date('Y-m-d'),
                'status'            => 0,
                'company_id'        => $company->id,
                'outlet_id'         => $input['outlet_id'],
                'user_id'           => $input['user_id'],
            ];
            // dd($quotation_data);
            $quotation = Quotation::create($quotation_data);

            if ($quotation) {
                $total = 0;
                $stock = 0;
                foreach ($carts as $key => $cart) {
                    $product = Product::find($key);
                    // dd($product);
                    $quotation_detail_data = [
                        'quotation_id'          => $quotation->id,
                        'product_id'            => $key,
                        'qty'                   => $cart['qty'],
                        'price'                 => $product->price,
                        'laba'                  => $product->laba,
                        'product_name'          => $product->name,
                        'product_description'   => $product->description,
                    ];
                    $quotation_detail_data = QuotationDetail::create($quotation_detail_data);

                    $total += ($product->price * $cart['qty']);
                    $stock = ($product->stock - $cart['qty']);
                    $product->update(['stock'=> $stock]);
                }

                $quotation = Quotation::find($quotation->id);
                $quotation->update(['total'=> $total]);

                session()->forget('cart');
                session()->forget('cart_total');
                session()->forget('cart_grand_total');

                return redirect()->route('order.invoice', $quotation->id);
            }


            return back()->withInput();
          } catch (\Exception $e) {
            return  back()->withInput();
          }
    }

    public function invoice($id)
    {
        $quotation = Quotation::with('quotation_details')->find($id);

        return view('pages.'.$this->view. 'invoice', compact('quotation'));
    }

}

resources/views/pages/admin/orders/action.blade.php
<div class="dropdown">
    <button class="btn btn-sm btn-primary dropdown-toggle" type="button" id="dropdownMenuAction" data-bs-toggle="dropdown"
        aria-expanded="false">
        Action
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuAction">
        <li><a class="dropdown-item edit-btn" href="{{ route('admin.orders.edit', $id) }}">Edit</a></li>
        <li><a class="dropdown-item" href="{{ route('admin.orders.show', $id) }}">Show</a></li>
        <li><a class="dropdown-item" href="{{ route('admin.invoice.index', ['orderId' => $id]) }}">Invoice</a></li>
        <li>
            <a class="dropdown-item" href="{{ route('admin.orders.print-preview', $id) }}" target="_blank">Preview Print Order</a>
            <a class="dropdown-item" href="{{ route('admin.orders.print-struk', $id) }}" target="_blank">Preview Print Struk</a>
        </li>
        <li>
            <a class="dropdown-item" href="{{ route('admin.orders.print', $id) }}">Download Order</a>
        </li>
        <li>
            <hr class="dropdown-divider">
        </li>
        <li><a class="dropdown-item delete-btn" data-id="{{ $id }}" href="#">Delete</a></li>
    </ul>
</div>

resources/views/pages/admin/orders/create.blade.php
@extends('layouts.admin.app')

@section('content')
    <div id="kt_content_container" class="d-flex flex-column-fluid align-items-start container-xxl">
        <div class="content flex-row-fluid" id="kt_content">
            <!--begin::Form-->
            <form method="post" action="{{ route('admin.orders.store') }}" enctype="multipart/form-data"
                class="form d-flex flex-column flex-lg-row form needs-validation" id="order-form" autocomplete="off"
                novalidate>
                <!-- <form id="kt_ecommerce_edit_order_form" class="" data-kt-redirect="/Adminin/demo20/../demo20/apps/ecommerce/sales/listing.html"> -->
                <!--begin::Aside column-->
                @csrf

                @include('pages.' . $path . '.' . $view . '.form')

                <!--end::Main column-->
            </form>
            <!--end::Form-->
        </div>
    </div>
@endsection

resources/views/pages/admin/orders/edit.blade.php
@extends('layouts.admin.app')
@section('content')
    <div id="kt_content_container" class="d-flex flex-column-fluid align-items-start container-xxl">
        <div class="content flex-row-fluid" id="kt_content">
            <!--begin::Form-->
            <form method="post" action="{{ route('admin.orders.update', $order->id) }}" enctype="multipart/form-data"
                class="form d-flex flex-column flex-lg-row form needs-validation" id="order-form" autocomplete="off"
                novalidate>
                <!-- <form id="kt_ecommerce_edit_order_form" class="" data-kt-redirect="/Adminin/demo20/../demo20/apps/ecommerce/sales/listing.html"> -->
                <!--begin::Aside column-->
                @csrf

                @include('pages.' . $path . '.' . $view . '.form')

                <!--end::Main column-->
            </form>
            <!--end::Form-->
        </div>
    </div>
@endsection

resources/views/pages/admin/orders/index.blade.php
@extends('layouts.admin.app')
@section('content')
    <!--begin::Container-->
    <div id="container" class="d-flex flex-column-fluid align-items-start container-xxl">
        <!--begin::Post-->
        <div class="content flex-row-fluid">
            <!--begin::Card-->
            <div class="card">
                <div class="card-header border-0 pt-6 d-flex justify-content-end">
                    <a href="{{ route('admin.orders.create') }}" class="btn btn-primary btn-hover-scale mt-3">
                        <i class="la la-plus"></i>
                        Create
                    </a>
                </div>
                <!--begin::Card body-->
                <div class="card-body py-4">
                    <!--begin::Table-->
                    <div class="table-responsive">
                        {{ $dataTable->table() }}
                    </div>
                    <!--end::Table-->
                </div>
                <!--end::Card body-->
            </div>
            <!--end::Card-->
        </div>
        <!--end::Post-->
    </div>
@endsection

@push('scripts')
{{ $dataTable->scripts() }}
    <script>
        $(document).ready(function() {
            let method = 'POST'

            //DELETE
            $(document).on('click', '.delete-btn', function() {
                Swal.fire({
                    title: 'Are you sure',
                    icon: 'info',
                    showDenyButton: true,
                    confirmButtonText: 'Yes',
                    denyButtonText: `No`,
                }).then((result) => {
                    if (result.isConfirmed) {
                        const url = '{{ url('admin/orders/destroy') }}/' + $(this).data('id')
                        $.ajax({
                            url: url,
                            method: 'DELETE',
                            headers: {
                                'X-CSRF-TOKEN': '{{ csrf_token() }}'
                            }
                        }).done(response => {
                            console.log(response)
                            Swal.fire({
                                icon: 'success',
                                title: 'Success',
                                message: response.message
                            })
                            $('.dataTable').DataTable().ajax.reload()
                        })
                    }
                })
            })
        })

        $(function() {
            var table = $('.data-table').DataTable({
                columnDefs: [{
                    targets: 'no-sort',
                    orderable: false
                }],
                dom: '<"row"<"col-sm-6"Bl><"col-sm-6"f>>' +
                    '<"row"<"col-sm-12"<"table-responsive"tr>>>' +
                    '<"row"<"col-sm-5"i><"col-sm-7"p>>',
                fixedHeader: {
                    header: true
                },
                dom: 'Bfrtip',
                buttons: [{
                        extend: 'excelHtml5',
                        className: 'export-button',
                        title: 'Excel Order',
                        footer: true,
                        exportOptions: {
                            columns: [0, 1, 2, 3, 4, 5, 6]
                        }
                    }, {
                        extend: 'csvHtml5',
                        className: 'export-button',
                        title: 'CSV Order',
                        footer: true,
                        exportOptions: {
                            columns: [0, 1, 2, 3, 4, 5, 6]
                        }
                    },
                    {
                        extend: 'pdfHtml5',
                        className: 'export-button',
                        title: 'PDF Order',
                        footer: true,
                        exportOptions: {
                            columns: [0, 1, 2, 3, 4, 5, 6]
                        }
                    },

                ],
                processing: true,
                serverSide: true,
                ajax: {
                    url: "{{ route('admin.orders.index') }}",
                },
                columns: [{
                        data: 'id',
                        render: function(data, type, full, meta) {
                            return meta.settings._iDisplayStart + meta.row + 1;
                        }
                    },
                    {
                        data: 'customer.name',
                        name: 'customer.name'
                    },
                    {
                        data: 'company.name',
                        name: 'company.name',
                    },
                    {
                        data: 'order_code',
                        name: 'order_code'
                    },
                    {
                        data: 'total',
                        name: 'total'
                    },
                    {
                        data: 'paid',
                        name: 'paid'
                    },
                    {
                        data: 'status',
                        name: 'status'
                    },
                    {
                        data: 'action',
                        name: 'action',
                        orderable: false,
                        searchable: false
                    },
                ]
            });
        });
    </script>
@endpush

resources/views/pages/admin/orders/script.blade.php
<script>
        {{$dataTable->scripts()}}

        $(document).ready(function() {
            let method = 'POST'

            //STORE
            $('#product-form').submit(function(e) {
                e.preventDefault()
                const payload = $(this).serialize()
                const url = $(this).attr('action')
                const validator = document.getElementById('product-form').checkValidity()

                if(validator) {
                    $.ajax({
                        url: url,
                        method: method,
                        data: payload
                    })
                    .done(response => {
                        if(response.success) {
                            Swal.fire({
                                icon: 'success',
                                title: 'Success',
                                text: response.message
                            })

                            $('.dataTable').DataTable().ajax.reload()
                            $('#product-modal').modal('hide')
                        }
                    })
                    .fail(response => {
                        Swal.fire({
                            icon: 'error',
                            title: 'Error',
                            text: response.responseJSON.message
                        })
                    })
                }

            })


            //DELETE
            $(document).on('click', '.delete-btn', function(){
                Swal.fire({
                    title: 'Are you sure',
                    icon: 'info',
                    showDenyButton: true,
                    confirmButtonText: 'Yes',
                    denyButtonText: `No`,
                    }).then((result) => {
                    /* Read more about isConfirmed, isDenied below */
                    if (result.isConfirmed) {
                        const url = '{{ url("admin/products") }}/' + $(this).data('id')
                        $.ajax({
                            url: url,
                            method: 'DELETE',
                            headers: {
                                'X-CSRF-TOKEN': '{{ csrf_token() }}'
                            }
                        }).done(response => {
                            console.log(response)
                            Swal.fire({
                                icon: 'success',
                                title: 'Success',
                                message: response.message
                            })
                            $('.dataTable').DataTable().ajax.reload()
                        })
                    }
                })
            })

            //EDIT
            $(document).on('click', '.edit-btn', function(){
                const url = '{{ url("admin/products") }}/' + $(this).data('id')
                $('#product-form').attr('action', url)
                method = 'PUT'

                let data = {}
                $.get(url).done(response => {
                    if(response.success) data = response.data
                    setForm(data)
                    $('#product-modal').modal('show')
                })
            })

            function setForm(data) {
                $('input[name=name]').val(data.name)
                $('input[name=email]').val(data.email)
                $('input[name=username]').val(data.username)
                $('input[name=phone]').val(data.phone)
                $('input[name=address]').val(data.address)
            }

            $('.modal').on('hidden.bs.modal', function (event) {
                $('#user-form').attr('action', '{{ route("admin.users.store") }}')
                method = 'POST'
            })

        })

    </script>